from snakemake.utils import min_version
min_version("7.12.1")
configfile: "config/config.yaml"
SAMPLES = glob_wildcards(config["GENOMES"]+"/{samples}.fa").samples
num = config["GENE_COUNT"]
IDS = list(range(1,num+1))
mode = config.get("mode","accurate")

if (mode == "fast"):
	include: "rules/mashtree.smk"
elif (mode == "balanced"):
	include: "rules/align.smk"
	include: "rules/astral.smk"
	include: "rules/sampling.smk"
	include: "rules/fasttree.smk"
else:
	include: "rules/align.smk"
	include: "rules/astral.smk"
	include: "rules/sampling.smk"
	include: "rules/tree.smk"
	
rule all:
	input:
		config["OUT_DIR"]+"/roadies.nwk"