ALL_OUT_DIR: converge_files
CONTINUITY_HIGH: 85
CONTINUITY_LOW: 85
COVERAGE_HIGH: 85
COVERAGE_LOW: 85
FILTERFRAGMENTS: 0.5
GENE_COUNT: 50
GENOMES: test/test_data
IDENTITY_HIGH: 40
IDENTITY_LOW: 65
LENGTH: 500
MASKSITES: 0.02
MAX_DUP: 10
MIN_ALIGN: 4
NUM_INSTANCES: 4
OUT_DIR: output_files
REFERENCE: null
SCORES: HOXD55.q
STEPS: 1
SUPPORT_THRESHOLD: 0.95
THRESHOLD: 0.1
UPPER_CASE: 0.9
